name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.local/bin/
          poetry config virtualenvs.create false





      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Export dependencies to requirements.txt
        run: |
          poetry export --without-hashes -f requirements.txt --output ./requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
          
      - name: Build Docker image
        if: success()
        run: |
          docker build -t myimage:${{ github.sha }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push myimage:${{ github.sha }}
